import type { Heat, Ingredient, Recipe, RecipeStep, WaterTemperature } from "@/lib/recipes";

const VERIFIED_AT = "2026-08-11";
const GUIDELINE_URL = "https://dg.cnsoc.org/";

export type AdditionalRecipe = {
  slug: string;
  title: string;
  category: string;
  tags: string[];
  featureTags: [string, string, string];
  dietType: Recipe["dietType"];
  nutritionRoles: Recipe["nutritionRoles"];
  cookingMethod: string;
  spiceLevel: Recipe["spiceLevel"];
  difficulty: Recipe["difficulty"];
  prepMinutes: number;
  activeMinutes: number;
  waitMinutes: number;
  servings: number;
  ingredients: Ingredient[];
  steps: RecipeStep[];
  tips: [string, string];
  failurePoint: string;
  safetyNote: string;
  videoUrl: string;
  videoTitle: string;
  videoCreator: string;
};

export function ingredient(name: string, amount: number, unit: string, group: Ingredient["group"], note?: string): Ingredient {
  return { name, amount, unit, group, note };
}

export function step(
  title: string,
  text: string,
  heat: Heat,
  waterTemperature: WaterTemperature,
  oilTemperature: string,
  time: string,
  timerSeconds: number,
  cue: string,
  ingredients: string[],
  safety?: string,
): RecipeStep {
  return {
    title,
    text,
    heat,
    waterTemperature,
    oilTemperature,
    time,
    timerSeconds,
    cue,
    ingredients,
    safety,
  };
}

function allergensFor(ingredients: Ingredient[]) {
  const names = ingredients.map((item) => item.name).join("、");
  return [
    /鸡蛋|蛋清/.test(names) ? "蛋" : "",
    /面粉|面皮|面条/.test(names) ? "麸质" : "",
    /豆腐|豆瓣酱|豆豉|生抽|老抽|黄豆酱/.test(names) ? "大豆" : "",
    /鱼/.test(names) ? "鱼类" : "",
    /虾/.test(names) ? "甲壳类" : "",
  ].filter(Boolean);
}

export function buildAdditionalRecipe(input: AdditionalRecipe): Recipe {
  const bilibiliSearchUrl = `https://search.bilibili.com/all?keyword=${encodeURIComponent(`${input.title} 做法`)}`;
  return {
    slug: input.slug,
    title: input.title,
    summary: `${input.featureTags.join("、")}的${input.title}。`,
    image: "",
    imageVerified: false,
    category: input.category,
    tags: [...new Set([input.category, ...input.tags])],
    featureTags: input.featureTags,
    aliases: [],
    dietType: input.dietType,
    nutritionRoles: input.nutritionRoles,
    cookingMethod: input.cookingMethod,
    spiceLevel: input.spiceLevel,
    allergens: allergensFor(input.ingredients),
    difficulty: input.difficulty,
    prepMinutes: input.prepMinutes,
    activeMinutes: input.activeMinutes,
    waitMinutes: input.waitMinutes,
    cookMinutes: input.activeMinutes + input.waitMinutes,
    servings: input.servings,
    likes: 0,
    weeklyLikes: 0,
    ingredients: input.ingredients,
    steps: input.steps,
    tips: input.tips,
    failurePoints: [input.failurePoint],
    safetyNote: input.safetyNote,
    editorialStatus: "draft",
    bilibiliVideoUrl: input.videoUrl,
    bilibiliSearchUrl,
    videoTitle: input.videoTitle,
    videoCreator: input.videoCreator,
    videoVerifiedAt: VERIFIED_AT,
    sources: [
      { name: `${input.videoCreator}：${input.videoTitle}`, url: input.videoUrl, type: "video", verifiedAt: VERIFIED_AT },
      { name: "中国居民膳食指南（2022）", url: GUIDELINE_URL, type: "guideline", verifiedAt: VERIFIED_AT },
    ],
  };
}

const additions: AdditionalRecipe[] = [
  {
    slug: "twice-cooked-pork",
    title: "回锅肉",
    category: "荤菜",
    tags: ["经典川菜"],
    featureTags: ["咸香微辣", "肉片焦香", "蒜苗爽脆"],
    dietType: "半荤素",
    nutritionRoles: ["蛋白质", "蔬菜"],
    cookingMethod: "煮后回锅",
    spiceLevel: 2,
    difficulty: 2,
    prepMinutes: 15,
    activeMinutes: 12,
    waitMinutes: 20,
    servings: 4,
    ingredients: [
      ingredient("带皮二刀肉", 500, "g", "主料", "整块洗净"),
      ingredient("蒜苗", 180, "g", "辅料", "蒜白斜切、蒜叶切段"),
      ingredient("姜", 15, "g", "辅料", "切片"),
      ingredient("郫县豆瓣酱", 25, "g", "调料"),
      ingredient("豆豉", 8, "g", "调料"),
      ingredient("甜面酱", 10, "g", "调料"),
      ingredient("白糖", 3, "g", "调料"),
      ingredient("食用油", 10, "ml", "调料"),
      ingredient("清水", 1500, "ml", "辅料", "煮肉用"),
    ],
    steps: [
      step("整块煮到七成熟", "二刀肉冷水入锅，加入清水和姜，大火煮开后撇沫，转中火煮 18–20 分钟。", "中火", "冷水", "不适用", "20 分钟", 1200, "筷子可插入肉皮，切开中心没有明显血水但肉质仍紧实。", ["带皮二刀肉", "清水", "姜"], "煮肉汤仍含生肉汁，接触过的器具要清洗。"),
      step("冷却切薄片", "肉块捞出擦干，放至不烫手后切成约 2mm 薄片；蒜苗的蒜白和蒜叶分开放。", "不适用", "不适用", "不适用", "6 分钟", 360, "肉片厚薄接近，蒜白与蒜叶没有混放。", ["带皮二刀肉", "蒜苗"]),
      step("煸出灯盏窝", "炒锅中火预热，倒入食用油，下肉片摊开煸炒 3–4 分钟。", "中火", "不适用", "油面轻微波纹", "4 分钟", 240, "肉片吐油、边缘微卷，肥肉变得半透明。", ["带皮二刀肉", "食用油"]),
      step("小火炒香酱料", "把肉片拨到锅边，转小火加入郫县豆瓣酱、豆豉和甜面酱，炒 40 秒后与肉片翻匀。", "小火", "不适用", "不适用", "40 秒", 40, "酱料炒出红油和香气，没有焦黑。", ["郫县豆瓣酱", "豆豉", "甜面酱", "带皮二刀肉"]),
      step("先下蒜白", "加入蒜苗白和白糖，转大火翻炒 45 秒。", "大火", "不适用", "不适用", "45 秒", 45, "蒜白断生、颜色鲜亮，肉片均匀裹酱。", ["蒜苗", "白糖"]),
      step("蒜叶断生即出锅", "加入蒜苗叶，大火翻炒 20–30 秒立即关火装盘。", "大火", "不适用", "不适用", "30 秒", 30, "蒜叶刚变软仍鲜绿，锅底无大量油汁。", ["蒜苗"]),
    ],
    tips: ["煮好的肉彻底擦干再切，煸炒时不易溅油。", "豆瓣酱、豆豉和甜面酱已有咸味，本配方不再额外加盐。"],
    failurePoint: "肉片太厚会肥腻，蒜苗叶下锅过早会发黄发软。",
    safetyNote: "猪肉应彻底加热；切开最厚处确认无生肉色，熟肉不得放回接触过生肉的盘子。",
    videoUrl: "https://www.bilibili.com/video/BV1wt411y7vE/",
    videoTitle: "【火筵家常 回锅肉】火哥的菜：正宗四川回锅肉，猪肉川菜之王最传统做法详解",
    videoCreator: "火筵家常",
  },
  {
    slug: "beer-duck",
    title: "啤酒鸭",
    category: "荤菜",
    tags: ["下饭菜"],
    featureTags: ["酱香微辣", "鸭肉软嫩", "麦香浓郁"],
    dietType: "荤",
    nutritionRoles: ["蛋白质"],
    cookingMethod: "红烧",
    spiceLevel: 2,
    difficulty: 3,
    prepMinutes: 18,
    activeMinutes: 18,
    waitMinutes: 35,
    servings: 5,
    ingredients: [
      ingredient("鸭腿", 900, "g", "主料", "剁 4cm 块"),
      ingredient("啤酒", 500, "ml", "辅料"),
      ingredient("青椒", 150, "g", "辅料", "切块"),
      ingredient("姜", 20, "g", "辅料", "切片"),
      ingredient("蒜", 20, "g", "辅料"),
      ingredient("干辣椒", 6, "g", "调料", "剪段"),
      ingredient("八角", 2, "个", "调料"),
      ingredient("生抽", 25, "ml", "调料"),
      ingredient("老抽", 6, "ml", "调料"),
      ingredient("白糖", 8, "g", "调料"),
      ingredient("食盐", 2, "g", "调料"),
      ingredient("食用油", 12, "ml", "调料"),
    ],
    steps: [
      step("鸭块焯水洗净", "鸭块冷水下锅，大火煮开 3 分钟，撇去浮沫后捞出，用温水冲净并沥干。", "大火", "冷水", "不适用", "6 分钟", 360, "鸭块表面无血沫，沥水后不再滴水。", ["鸭腿"], "焯水只用于去除血沫，鸭肉此时并未熟透。"),
      step("煸出鸭油", "炒锅中火预热后倒入食用油，下鸭块摊开煸炒 5 分钟。", "中火", "不适用", "油面轻微波纹", "5 分钟", 300, "鸭皮收紧微黄，锅中析出鸭油。", ["鸭腿", "食用油"]),
      step("炒香辛料", "加入姜、蒜、干辣椒和八角，中火翻炒 1 分钟。", "中火", "不适用", "不适用", "1 分钟", 60, "姜蒜和香料出香但没有焦黑。", ["姜", "蒜", "干辣椒", "八角"]),
      step("调味上色", "加入生抽、老抽和白糖，翻炒 1 分钟，让鸭块均匀上色。", "中火", "不适用", "不适用", "1 分钟", 60, "鸭块呈均匀棕红色，糖没有粘底焦化。", ["生抽", "老抽", "白糖", "鸭腿"]),
      step("倒啤酒小火焖", "倒入啤酒，大火煮沸 2 分钟后转小火，盖盖留缝焖 30–35 分钟。", "小火", "热水", "不适用", "35 分钟", 2100, "鸭肉最厚处无血水，筷子可穿入，锅中仍有少量汤汁。", ["啤酒", "鸭腿"], "鸭肉最厚处中心温度需达到 74°C。"),
      step("青椒收汁", "加入青椒和食盐，转大火翻炒 2 分钟收汁，汤汁能薄薄挂在鸭块表面时关火。", "大火", "不适用", "不适用", "2 分钟", 120, "青椒断生仍翠绿，鸭块完全熟透，酱汁没有焦味。", ["青椒", "食盐", "鸭腿"]),
    ],
    tips: ["鸭块焯水后必须沥干，防止煸炒时大量溅油。", "使用普通淡色拉格啤酒即可，苦味很重的啤酒会让成品发苦。"],
    failurePoint: "汤汁快干时必须勤翻动，糖、老抽和啤酒浓缩后很容易焦苦。",
    safetyNote: "鸭肉属于禽肉，最厚处中心应达到 74°C，贴骨位置不得带血色。",
    videoUrl: "https://www.bilibili.com/video/BV1n84y1g7kK/",
    videoTitle: "一道啤酒鸭，征服了所有亲朋好友，吃过都夸，鲜香入味，辣的过瘾，下酒又下饭！超详细做法分享给你们，新手也能做成功",
    videoCreator: "月月在做饭",
  },
  {
    slug: "sichuan-boiled-pork",
    title: "水煮肉片",
    category: "荤菜",
    tags: ["经典川菜"],
    featureTags: ["麻辣鲜香", "肉片滑嫩", "汤红味浓"],
    dietType: "半荤素",
    nutritionRoles: ["蛋白质", "蔬菜"],
    cookingMethod: "水煮",
    spiceLevel: 3,
    difficulty: 3,
    prepMinutes: 22,
    activeMinutes: 18,
    waitMinutes: 10,
    servings: 4,
    ingredients: [
      ingredient("猪里脊", 400, "g", "主料", "逆纹切 3mm 片"),
      ingredient("黄豆芽", 250, "g", "辅料"),
      ingredient("莴笋", 200, "g", "辅料", "切薄片"),
      ingredient("鸡蛋清", 30, "g", "辅料", "约 1 个"),
      ingredient("玉米淀粉", 18, "g", "调料"),
      ingredient("郫县豆瓣酱", 30, "g", "调料"),
      ingredient("生抽", 15, "ml", "调料"),
      ingredient("料酒", 10, "ml", "调料"),
      ingredient("干辣椒", 12, "g", "调料"),
      ingredient("花椒", 5, "g", "调料"),
      ingredient("蒜", 20, "g", "辅料", "切末"),
      ingredient("食盐", 3, "g", "调料"),
      ingredient("食用油", 35, "ml", "调料"),
      ingredient("清水", 900, "ml", "辅料"),
    ],
    steps: [
      step("肉片上浆", "猪里脊加入料酒、生抽、鸡蛋清和玉米淀粉，沿同一方向抓拌 2 分钟，冷藏静置 10 分钟。", "不适用", "不适用", "不适用", "12 分钟", 720, "肉片表面形成均匀薄浆，没有流动蛋清。", ["猪里脊", "料酒", "生抽", "鸡蛋清", "玉米淀粉"], "腌肉容器和筷子不得接触熟食。"),
      step("炒熟垫底蔬菜", "锅中加食用油 10ml，中火先炒黄豆芽 2 分钟，再加莴笋和食盐 1g 炒 1 分钟，盛入大碗。", "中火", "不适用", "油面轻微波纹", "3 分钟", 180, "豆芽无生豆味，莴笋断生仍脆。", ["黄豆芽", "莴笋", "食用油", "食盐"]),
      step("炒出红汤", "原锅加入食用油 10ml，小火炒郫县豆瓣酱 1 分钟，加入一半蒜末炒香，再倒入清水煮沸。", "中火", "热水", "油面温热不冒烟", "4 分钟", 240, "汤色红亮，豆瓣酱香气明显。", ["食用油", "郫县豆瓣酱", "蒜", "清水"]),
      step("肉片逐片滑熟", "汤保持微沸，肉片逐片分散下锅，全部下完后用勺背轻推，煮 90 秒至肉片完全变白。", "中火", "沸水", "不适用", "90 秒", 90, "肉片舒展、中心无粉红色，汤面重新微沸。", ["猪里脊"], "猪肉必须完全熟透，最厚肉片切开不得呈粉红色。"),
      step("连汤倒入碗中", "加入剩余食盐，把肉片和汤倒在垫底蔬菜上，表面放剩余蒜末。", "不适用", "不适用", "不适用", "1 分钟", 60, "肉片均匀铺开，蒜末集中在表面便于泼油。", ["食盐", "蒜", "猪里脊", "黄豆芽", "莴笋"]),
      step("辣椒花椒泼油", "干辣椒和花椒放在肉片表面；剩余食用油 15ml 加热到约七成热，离火后立即淋在香料上。", "中火", "不适用", "油面波纹明显但不冒浓烟", "40 秒", 40, "香料发出明显滋啦声和麻辣香气，没有焦黑。", ["干辣椒", "花椒", "食用油"], "泼油时碗必须耐热、表面无水，面部和手远离热油。"),
    ],
    tips: ["肉片要逆纹切薄，淀粉只形成薄浆，过多会使汤浑。", "肉片下锅后不要持续大力搅动，定型后再轻推。"],
    failurePoint: "汤大滚或肉片久煮都会使里脊变柴，肉片变白熟透后应立即离火。",
    safetyNote: "猪肉片必须完全熟透；泼热油时使用干燥耐热容器，避免水滴引起爆溅。",
    videoUrl: "https://www.bilibili.com/video/BV1fk4y1J7vK/",
    videoTitle: "手把手教你做水煮肉片，学会一招，肉片鲜香滑嫩，比大厨做的还香",
    videoCreator: "老东北美食",
  },
  {
    slug: "pickled-cabbage-fish",
    title: "酸菜鱼",
    category: "海鲜",
    tags: ["经典川菜"],
    featureTags: ["酸辣开胃", "鱼片嫩滑", "汤鲜味浓"],
    dietType: "半荤素",
    nutritionRoles: ["蛋白质", "蔬菜"],
    cookingMethod: "酸汤煮",
    spiceLevel: 2,
    difficulty: 4,
    prepMinutes: 28,
    activeMinutes: 22,
    waitMinutes: 10,
    servings: 5,
    ingredients: [
      ingredient("黑鱼片", 600, "g", "主料", "购买已去刺鱼片并复查"),
      ingredient("鱼骨", 400, "g", "辅料", "斩段"),
      ingredient("四川酸菜", 350, "g", "辅料", "冲洗后切段"),
      ingredient("鸡蛋清", 30, "g", "辅料"),
      ingredient("玉米淀粉", 18, "g", "调料"),
      ingredient("姜", 20, "g", "辅料", "切片"),
      ingredient("蒜", 20, "g", "辅料", "切末"),
      ingredient("泡椒", 25, "g", "调料", "切段"),
      ingredient("白胡椒粉", 2, "g", "调料"),
      ingredient("料酒", 15, "ml", "调料"),
      ingredient("食盐", 3, "g", "调料"),
      ingredient("食用油", 25, "ml", "调料"),
      ingredient("热水", 1400, "ml", "辅料"),
    ],
    steps: [
      step("复查鱼刺并上浆", "逐片按压检查鱼刺；鱼片加入料酒 10ml、食盐 1g、白胡椒粉 1g、鸡蛋清和玉米淀粉抓匀，冷藏 10 分钟。", "不适用", "冷水", "不适用", "12 分钟", 720, "鱼片表面有均匀薄浆，未发现硬刺。", ["黑鱼片", "料酒", "食盐", "白胡椒粉", "鸡蛋清", "玉米淀粉"], "鱼片必须逐片检查鱼刺，处理生鱼后清洁刀板和双手。"),
      step("煎香鱼骨", "锅中火预热后倒入食用油 15ml，鱼骨擦干后下锅，每面煎约 2 分钟，再加入姜和剩余料酒。", "中火", "不适用", "油面出现细小波纹", "5 分钟", 300, "鱼骨表面微黄，姜香明显。", ["鱼骨", "食用油", "姜", "料酒"]),
      step("炒酸菜泡椒", "加入酸菜、泡椒和一半蒜末，中火翻炒 3 分钟。", "中火", "不适用", "不适用", "3 分钟", 180, "酸菜水汽减少，酸香和泡椒香气明显。", ["四川酸菜", "泡椒", "蒜"]),
      step("大火熬白鱼汤", "倒入热水，大火煮 8 分钟，撇去浮沫；加入剩余食盐和白胡椒粉。", "大火", "热水", "不适用", "8 分钟", 480, "汤色变白、持续沸腾，鱼骨完全熟透。", ["热水", "食盐", "白胡椒粉", "鱼骨"]),
      step("捞出鱼骨酸菜", "把鱼骨和酸菜捞入大碗，鱼汤重新保持微沸。", "中火", "沸水", "不适用", "2 分钟", 120, "碗底铺好鱼骨酸菜，锅中只留清晰鱼汤。", ["鱼骨", "四川酸菜"]),
      step("分散滑熟鱼片", "鱼片逐片放入微沸鱼汤，全部下完后轻推，煮 60–90 秒至完全变白卷起，连汤倒入碗中。", "中火", "沸水", "不适用", "90 秒", 90, "鱼片完全不透明、能轻松分开，中心温度达到 63°C。", ["黑鱼片"]),
      step("蒜末泼油", "鱼片表面放剩余蒜末；剩余食用油 10ml 加热后离火淋上。", "中火", "不适用", "油面明显波纹但不冒浓烟", "30 秒", 30, "蒜香被激发，没有焦黑。", ["蒜", "食用油"], "耐热碗必须干燥稳固，泼油时远离面部。"),
    ],
    tips: ["优先购买正规渠道已处理的黑鱼片，回家仍要逐片复查鱼刺。", "鱼片只在微沸汤中滑熟，持续大滚会脱浆并让鱼肉变柴。"],
    failurePoint: "鱼片一次成团倒入会粘连且外熟内生，必须逐片分散下锅。",
    safetyNote: "鱼片和鱼骨中心均应达到 63°C；食用前再次检查细刺，儿童和老人由成人剔刺。",
    videoUrl: "https://www.bilibili.com/video/BV1gJ411B7KQ/",
    videoTitle: "超详细的酸菜鱼教程，保你个个会杀鱼个个会片鱼~",
    videoCreator: "马壮实Hera",
  },
  {
    slug: "di-san-xian",
    title: "地三鲜",
    category: "蔬菜",
    tags: ["东北家常菜"],
    featureTags: ["咸鲜下饭", "外香里软", "三蔬入味"],
    dietType: "素",
    nutritionRoles: ["蔬菜"],
    cookingMethod: "煎烧",
    spiceLevel: 0,
    difficulty: 2,
    prepMinutes: 15,
    activeMinutes: 18,
    waitMinutes: 0,
    servings: 4,
    ingredients: [
      ingredient("长茄子", 400, "g", "主料", "切滚刀块"),
      ingredient("土豆", 350, "g", "辅料", "切 5mm 片"),
      ingredient("青椒", 160, "g", "辅料", "切块"),
      ingredient("蒜", 15, "g", "辅料", "切末"),
      ingredient("生抽", 18, "ml", "调料"),
      ingredient("蚝油", 12, "ml", "调料"),
      ingredient("白糖", 4, "g", "调料"),
      ingredient("食盐", 2, "g", "调料"),
      ingredient("玉米淀粉", 6, "g", "调料"),
      ingredient("清水", 80, "ml", "辅料"),
      ingredient("食用油", 35, "ml", "调料"),
    ],
    steps: [
      step("调好碗汁", "生抽、蚝油、白糖、食盐、玉米淀粉和清水搅匀，使用前再搅一次。", "不适用", "冷水", "不适用", "2 分钟", 120, "糖盐溶解，淀粉没有结块。", ["生抽", "蚝油", "白糖", "食盐", "玉米淀粉", "清水"]),
      step("土豆煎到熟透", "平底锅中火预热，倒入食用油 15ml，土豆单层煎 6–8 分钟，中途翻面。", "中火", "不适用", "油面出现细小波纹", "8 分钟", 480, "土豆两面金黄，筷子能轻松穿透且中心无硬芯。", ["土豆", "食用油"]),
      step("茄子煎软", "土豆盛出；原锅加入食用油 15ml，下茄子中火煎炒 5–6 分钟。", "中火", "不适用", "油面轻微波纹", "6 分钟", 360, "茄子明显缩小变软，表面微黄。", ["长茄子", "食用油"]),
      step("青椒蒜末爆香", "加入剩余食用油、青椒和蒜末，转大火翻炒 40 秒。", "大火", "不适用", "不适用", "40 秒", 40, "青椒断生仍翠绿，蒜香明显。", ["青椒", "蒜", "食用油"]),
      step("三蔬合炒挂汁", "土豆回锅，碗汁再次搅匀后沿锅边倒入，大火翻炒 45–60 秒。", "大火", "不适用", "不适用", "1 分钟", 60, "薄芡均匀包裹三种蔬菜，锅底没有生淀粉水。", ["土豆", "长茄子", "青椒", "清水", "玉米淀粉"]),
    ],
    tips: ["土豆切片后冲去表面淀粉并擦干，煎时更不易粘锅。", "家庭版采用煎制而不是宽油炸，茄子切后立即下锅可减少吸油。"],
    failurePoint: "土豆必须先完全煎熟；只看表面金黄、中心仍硬会直接影响成品。",
    safetyNote: "茄科蔬菜和土豆均应充分加热，发绿或严重发芽的土豆不得食用。",
    videoUrl: "https://www.bilibili.com/video/BV1iW411N7CY/",
    videoTitle: "厨师长教你一道北方菜：“地三鲜”的家常做法，味道很赞",
    videoCreator: "美食作家王刚R",
  },
  {
    slug: "fish-fragrant-eggplant",
    title: "鱼香茄子",
    category: "蔬菜",
    tags: ["经典川菜"],
    featureTags: ["酸甜微辣", "茄子软糯", "少油下饭"],
    dietType: "素",
    nutritionRoles: ["蔬菜"],
    cookingMethod: "煎烧",
    spiceLevel: 2,
    difficulty: 2,
    prepMinutes: 12,
    activeMinutes: 15,
    waitMinutes: 0,
    servings: 3,
    ingredients: [
      ingredient("长茄子", 500, "g", "主料", "切 6cm 条"),
      ingredient("郫县豆瓣酱", 18, "g", "调料"),
      ingredient("蒜", 15, "g", "辅料", "切末"),
      ingredient("姜", 8, "g", "辅料", "切末"),
      ingredient("生抽", 15, "ml", "调料"),
      ingredient("香醋", 18, "ml", "调料"),
      ingredient("白糖", 15, "g", "调料"),
      ingredient("玉米淀粉", 6, "g", "调料"),
      ingredient("清水", 100, "ml", "辅料"),
      ingredient("食用油", 25, "ml", "调料"),
    ],
    steps: [
      step("调鱼香汁", "生抽、香醋、白糖、玉米淀粉和清水搅匀。", "不适用", "冷水", "不适用", "2 分钟", 120, "糖和淀粉完全分散，碗底无粉团。", ["生抽", "香醋", "白糖", "玉米淀粉", "清水"]),
      step("茄子干锅煸软", "不粘锅中火预热，下茄子干锅煸 3 分钟，让表面水分蒸发。", "中火", "不适用", "干锅温热", "3 分钟", 180, "茄子表面发干、体积略缩小。", ["长茄子"]),
      step("少油煎到软糯", "倒入食用油 20ml，中火继续翻煎 5–6 分钟。", "中火", "不适用", "油面轻微波纹", "6 分钟", 360, "茄子完全变软，夹起可弯曲但没有碎烂。", ["长茄子", "食用油"]),
      step("炒香豆瓣姜蒜", "把茄子拨到锅边，加入剩余食用油、郫县豆瓣酱、姜末和蒜末，小火炒 40 秒。", "小火", "不适用", "不适用", "40 秒", 40, "豆瓣酱炒出红油，姜蒜未焦。", ["食用油", "郫县豆瓣酱", "姜", "蒜"]),
      step("倒汁收浓", "鱼香汁再次搅匀后倒入，转大火翻炒 1 分钟，芡汁沸腾透明后离火。", "大火", "不适用", "不适用", "1 分钟", 60, "酸甜汁均匀挂在茄子上，锅底无白色生粉。", ["长茄子", "生抽", "香醋", "白糖", "玉米淀粉", "清水"]),
    ],
    tips: ["茄子先干煸去除部分水汽，再加油更容易少油软化。", "香醋不要长时间熬煮，碗汁沸腾透明后立即离火以保留醋香。"],
    failurePoint: "豆瓣酱和糖都容易焦，炒酱必须小火，收汁阶段要持续翻动。",
    safetyNote: "茄子必须完全加热至软熟；发苦、腐烂或表皮异常的茄子不要使用。",
    videoUrl: "https://www.bilibili.com/video/BV1jL4y1K7WX/",
    videoTitle: "大厨教你鱼香茄子的家常做法，拒绝用宽油，软嫩鲜香，色香味俱全",
    videoCreator: "超子美食",
  },
  {
    slug: "tiger-skin-pepper",
    title: "虎皮青椒",
    category: "蔬菜",
    tags: ["下饭菜", "新手推荐"],
    featureTags: ["酸香微辣", "表皮焦香", "少油快手"],
    dietType: "素",
    nutritionRoles: ["蔬菜"],
    cookingMethod: "干煸",
    spiceLevel: 2,
    difficulty: 1,
    prepMinutes: 8,
    activeMinutes: 10,
    waitMinutes: 0,
    servings: 3,
    ingredients: [
      ingredient("薄皮青椒", 500, "g", "主料", "去蒂去籽并擦干"),
      ingredient("蒜", 15, "g", "辅料", "切末"),
      ingredient("生抽", 15, "ml", "调料"),
      ingredient("香醋", 18, "ml", "调料"),
      ingredient("白糖", 5, "g", "调料"),
      ingredient("食盐", 2, "g", "调料"),
      ingredient("食用油", 12, "ml", "调料"),
    ],
    steps: [
      step("青椒擦干压裂", "青椒去蒂去籽，冲洗后彻底擦干，用刀背轻拍出裂纹。", "不适用", "冷水", "不适用", "4 分钟", 240, "青椒表面干燥，每根有浅裂纹但没有完全破碎。", ["薄皮青椒"]),
      step("调酸香汁", "生抽、香醋、白糖和食盐搅匀。", "不适用", "不适用", "不适用", "1 分钟", 60, "糖盐溶解，料汁均匀。", ["生抽", "香醋", "白糖", "食盐"]),
      step("干锅煸出虎皮", "炒锅中火预热，不放油，下青椒用锅铲持续按压并翻面 5–6 分钟。", "中火", "不适用", "干锅温热，不冒烟", "6 分钟", 360, "青椒表面出现均匀焦斑和皱皮，椒肉开始变软。", ["薄皮青椒"]),
      step("蒜油增香", "青椒拨到一边，加入食用油和蒜末，小火炒 20 秒后与青椒翻匀。", "小火", "不适用", "油温热、蒜末周围有小泡", "20 秒", 20, "蒜香明显但没有焦黄。", ["食用油", "蒜", "薄皮青椒"]),
      step("烹汁入味", "倒入酸香汁，转中火翻炒 1 分钟，让青椒吸收料汁后立即装盘。", "中火", "不适用", "不适用", "1 分钟", 60, "青椒软而不烂，料汁基本收住，表面虎皮清晰。", ["薄皮青椒", "生抽", "香醋", "白糖", "食盐"]),
    ],
    tips: ["青椒表面必须擦干，干煸时才容易形成虎皮且不会爆溅。", "怕辣可以使用皱皮青椒或去净白色筋膜。"],
    failurePoint: "火太大会表面焦黑而内部仍生，应该用中火边按压边翻面。",
    safetyNote: "处理辣椒后立即洗手，不要揉眼；青椒应煸至椒肉完全变软后再食用。",
    videoUrl: "https://www.bilibili.com/video/BV16W411y7iq/",
    videoTitle: "厨师长教虎皮青椒的正宗做法，做虎皮不用油不用炸，步骤通俗易懂",
    videoCreator: "涛厨V",
  },
  {
    slug: "garlic-lettuce",
    title: "蒜蓉油麦菜",
    category: "蔬菜",
    tags: ["减脂餐", "新手推荐", "清淡恢复"],
    featureTags: ["蒜香清爽", "脆嫩翠绿", "三分钟快炒"],
    dietType: "素",
    nutritionRoles: ["蔬菜"],
    cookingMethod: "快炒",
    spiceLevel: 0,
    difficulty: 1,
    prepMinutes: 6,
    activeMinutes: 3,
    waitMinutes: 0,
    servings: 3,
    ingredients: [
      ingredient("油麦菜", 500, "g", "主料", "切 8cm 段并彻底沥干"),
      ingredient("蒜", 20, "g", "辅料", "切末"),
      ingredient("食盐", 2, "g", "调料"),
      ingredient("生抽", 8, "ml", "调料"),
      ingredient("食用油", 15, "ml", "调料"),
    ],
    steps: [
      step("分开菜梗和菜叶", "油麦菜洗净后充分甩干，切段并把较厚菜梗与菜叶分开放；蒜切末。", "不适用", "冷水", "不适用", "5 分钟", 300, "叶片无泥沙和明显水珠，菜梗菜叶分开。", ["油麦菜", "蒜"]),
      step("调简单料汁", "食盐和生抽搅匀备用。", "不适用", "不适用", "不适用", "30 秒", 30, "食盐基本溶解。", ["食盐", "生抽"]),
      step("低温爆香蒜末", "炒锅中火预热后倒入食用油，转小火加入蒜末炒 15–20 秒。", "小火", "不适用", "油面轻微波纹", "20 秒", 20, "蒜香明显，蒜末仍为浅色。", ["食用油", "蒜"]),
      step("先炒菜梗", "转大火加入菜梗，快速翻炒 35–40 秒。", "大火", "不适用", "不适用", "40 秒", 40, "菜梗颜色变亮、刚开始变软。", ["油麦菜"]),
      step("菜叶调味离火", "加入菜叶和料汁，大火翻炒 30–40 秒，菜叶刚塌软即关火装盘。", "大火", "不适用", "不适用", "40 秒", 40, "叶片翠绿脆嫩，锅底没有大量出水。", ["油麦菜", "食盐", "生抽"]),
    ],
    tips: ["叶片洗后要彻底沥干，带水下锅会降温并产生大量汤汁。", "菜梗和菜叶分时下锅，才能同时熟而不老。"],
    failurePoint: "蒜末焦黄会发苦，蒜香出现后应立即转大火下菜。",
    safetyNote: "叶菜要逐片冲洗并沥干；炒至叶片完全塌软、菜梗断生后食用。",
    videoUrl: "https://www.bilibili.com/video/BV1Tu4y1U7UV/",
    videoTitle: "简单易学的蒜蓉油麦菜！零难度家常小炒，最适合厨房新手的快手菜！",
    videoCreator: "胡扯日记",
  },
  {
    slug: "hot-sour-soup",
    title: "酸辣汤",
    category: "汤粥",
    tags: ["暖胃汤", "新手推荐"],
    featureTags: ["酸辣开胃", "汤羹顺滑", "配料丰富"],
    dietType: "半荤素",
    nutritionRoles: ["汤羹", "蔬菜", "蛋白质"],
    cookingMethod: "煮汤",
    spiceLevel: 2,
    difficulty: 2,
    prepMinutes: 15,
    activeMinutes: 12,
    waitMinutes: 0,
    servings: 4,
    ingredients: [
      ingredient("嫩豆腐", 200, "g", "主料", "切细条"),
      ingredient("猪里脊", 120, "g", "辅料", "切细丝"),
      ingredient("水发木耳", 80, "g", "辅料", "切丝"),
      ingredient("鲜香菇", 100, "g", "辅料", "切丝"),
      ingredient("鸡蛋", 1, "个", "辅料", "打散"),
      ingredient("香醋", 35, "ml", "调料"),
      ingredient("白胡椒粉", 2, "g", "调料"),
      ingredient("生抽", 15, "ml", "调料"),
      ingredient("食盐", 3, "g", "调料"),
      ingredient("玉米淀粉", 18, "g", "调料"),
      ingredient("芝麻油", 5, "ml", "调料"),
      ingredient("清水", 1200, "ml", "辅料"),
    ],
    steps: [
      step("肉丝焯到变色", "清水煮至微沸，下猪里脊丝轻轻拨散，煮 60 秒并撇去浮沫。", "中火", "沸水", "不适用", "1 分钟", 60, "肉丝完全变白，汤面无明显血沫。", ["猪里脊", "清水"], "猪肉丝必须完全变色。"),
      step("煮熟木耳香菇", "加入木耳和香菇，中火煮 3 分钟。", "中火", "沸水", "不适用", "3 分钟", 180, "木耳和香菇完全熟透，香菇香气进入汤中。", ["水发木耳", "鲜香菇"]),
      step("加入豆腐调底味", "轻轻滑入嫩豆腐，加入生抽和食盐，保持微沸煮 2 分钟。", "小火", "沸水", "不适用", "2 分钟", 120, "豆腐中心热透且没有碎散。", ["嫩豆腐", "生抽", "食盐"]),
      step("分次勾薄芡", "玉米淀粉加等量冷水调匀，分 2 次淋入汤中，每次轻推至重新沸腾。", "中火", "冷水", "不适用", "1 分钟", 60, "汤体略有稠度但仍可流动，没有淀粉团。", ["玉米淀粉"]),
      step("淋入蛋液", "汤保持微沸，蛋液沿锅边细流淋入，等待 10 秒后轻推形成蛋花。", "中火", "沸水", "不适用", "40 秒", 40, "蛋液完全凝固成均匀薄片。", ["鸡蛋"], "鸡蛋应完全凝固。"),
      step("关火后加酸辣", "关火后加入香醋、白胡椒粉和芝麻油，轻轻搅匀立即盛出。", "不适用", "不适用", "不适用", "30 秒", 30, "醋香和胡椒辛香清晰，汤羹顺滑不结团。", ["香醋", "白胡椒粉", "芝麻油"]),
    ],
    tips: ["醋和白胡椒粉关火后再加，酸香和辛香更清晰。", "必须先勾芡再淋蛋液，蛋花才能悬浮并形成薄片。"],
    failurePoint: "芡汁一次倒入容易结团，应分两次加入并等汤重新沸腾。",
    safetyNote: "猪肉与蛋液均须完全熟透；木耳应现泡现用，泡发后冷藏并尽快烹调。",
    videoUrl: "https://www.bilibili.com/video/BV1cR4y1472S/",
    videoTitle: "厨师长教你：“酸辣汤”的家常做法，鲜香暖胃，增加食欲助消化",
    videoCreator: "美食作家王刚R",
  },
  {
    slug: "preserved-egg-pork-porridge",
    title: "皮蛋瘦肉粥",
    category: "汤粥",
    tags: ["早餐", "老人友好"],
    featureTags: ["绵滑浓香", "肉丝鲜嫩", "暖胃早餐"],
    dietType: "半荤素",
    nutritionRoles: ["主食", "蛋白质", "汤羹"],
    cookingMethod: "煮粥",
    spiceLevel: 0,
    difficulty: 2,
    prepMinutes: 12,
    activeMinutes: 10,
    waitMinutes: 35,
    servings: 4,
    ingredients: [
      ingredient("大米", 150, "g", "主料", "淘洗后沥水"),
      ingredient("猪里脊", 150, "g", "辅料", "切细丝"),
      ingredient("皮蛋", 2, "个", "辅料", "去壳切小丁"),
      ingredient("姜", 10, "g", "辅料", "切细丝"),
      ingredient("料酒", 8, "ml", "调料"),
      ingredient("玉米淀粉", 5, "g", "调料"),
      ingredient("食盐", 3, "g", "调料"),
      ingredient("白胡椒粉", 1, "g", "调料"),
      ingredient("芝麻油", 4, "ml", "调料"),
      ingredient("清水", 1600, "ml", "辅料"),
    ],
    steps: [
      step("煮开米粥", "大米和清水一同入厚底锅，大火煮开后立即搅动锅底。", "大火", "冷水", "不适用", "8 分钟", 480, "整锅沸腾，米粒均匀悬浮且没有粘底。", ["大米", "清水"]),
      step("小火煮至开花", "转小火盖盖留缝煮 25–30 分钟，每 8 分钟沿锅底搅动一次。", "小火", "沸水", "不适用", "30 分钟", 1800, "米粒开花，粥体绵稠。", ["大米"], "留意锅中水量，避免粥体粘底焦糊。"),
      step("肉丝上浆", "煮粥期间，猪里脊加入料酒、玉米淀粉和食盐 1g抓匀，冷藏 10 分钟。", "不适用", "不适用", "不适用", "10 分钟", 600, "肉丝表面有薄浆，没有游离料汁。", ["猪里脊", "料酒", "玉米淀粉", "食盐"]),
      step("先煮姜丝皮蛋", "粥中加入姜丝和一半皮蛋丁，小火煮 5 分钟并搅动。", "小火", "沸水", "不适用", "5 分钟", 300, "皮蛋香气融入粥中，粥底保持顺滑。", ["姜", "皮蛋", "大米"]),
      step("分散下肉丝", "保持粥体微沸，肉丝逐条撒入并轻推，煮 3 分钟至完全变白。", "小火", "沸水", "不适用", "3 分钟", 180, "肉丝完全熟透、没有粉红色，彼此不结团。", ["猪里脊"], "猪肉丝中心应达到 71°C。"),
      step("剩余皮蛋调味", "加入剩余皮蛋、食盐、白胡椒粉和芝麻油，再煮 1 分钟后关火。", "小火", "沸水", "不适用", "1 分钟", 60, "皮蛋丁完整，粥体绵滑且调味均匀。", ["皮蛋", "食盐", "白胡椒粉", "芝麻油"]),
    ],
    tips: ["一半皮蛋先煮融味，另一半最后加入保留颗粒感。", "粥变稠后必须勤搅锅底，避免大米沉底焦糊。"],
    failurePoint: "肉丝成团下锅会外熟内生，应逐条抖散并保持粥体微沸。",
    safetyNote: "猪肉丝必须完全熟透；皮蛋应选择包装完整、有生产信息的合格产品。",
    videoUrl: "https://www.bilibili.com/video/BV1hs411Y7Tc/",
    videoTitle: "【美食台】皮蛋瘦肉粥，两种米让它绵滑浓香",
    videoCreator: "一条风味地图",
  },
  {
    slug: "chive-pockets",
    title: "韭菜盒子",
    category: "面食",
    tags: ["早餐面点"],
    featureTags: ["皮薄馅足", "外酥里软", "韭香鲜美"],
    dietType: "半荤素",
    nutritionRoles: ["主食", "蔬菜", "蛋白质"],
    cookingMethod: "煎制",
    spiceLevel: 0,
    difficulty: 3,
    prepMinutes: 30,
    activeMinutes: 22,
    waitMinutes: 20,
    servings: 4,
    ingredients: [
      ingredient("中筋面粉", 350, "g", "主料"),
      ingredient("温水", 210, "ml", "辅料", "约 35°C"),
      ingredient("韭菜", 350, "g", "辅料", "洗净彻底晾干后切碎"),
      ingredient("鸡蛋", 3, "个", "辅料", "打散"),
      ingredient("虾皮", 20, "g", "辅料"),
      ingredient("食盐", 4, "g", "调料"),
      ingredient("白胡椒粉", 1, "g", "调料"),
      ingredient("芝麻油", 8, "ml", "调料"),
      ingredient("食用油", 25, "ml", "调料"),
    ],
    steps: [
      step("和面醒面", "温水分次加入中筋面粉，揉成柔软无干粉面团，盖严醒 20 分钟。", "不适用", "温水", "不适用", "20 分钟", 1200, "面团柔软光滑，按压后能缓慢回弹。", ["中筋面粉", "温水"]),
      step("炒散鸡蛋", "炒锅中火预热，倒入食用油 10ml，蛋液下锅后快速划成小块，完全凝固立即盛出放凉。", "中火", "不适用", "油面轻微波纹", "1 分钟", 60, "鸡蛋成小块、完全凝固且没有焦边。", ["鸡蛋", "食用油"], "鸡蛋液必须完全凝固。"),
      step("调韭菜馅", "韭菜先与芝麻油拌匀，再加入放凉的鸡蛋、虾皮、食盐和白胡椒粉轻轻翻匀。", "不适用", "不适用", "不适用", "3 分钟", 180, "馅料松散，盆底没有析出大量水分。", ["韭菜", "芝麻油", "鸡蛋", "虾皮", "食盐", "白胡椒粉"]),
      step("擀皮包严", "面团分成 8 份，擀成中间略厚、边缘薄的圆皮，放馅后对折并捏紧边缘。", "不适用", "不适用", "不适用", "12 分钟", 720, "盒子封口完整，没有破皮漏馅。", ["中筋面粉", "韭菜", "鸡蛋"]),
      step("中小火煎第一面", "平底锅中火预热，倒入食用油 8ml，分批放入盒子后转中小火盖盖煎 3 分钟。", "小火", "不适用", "油面轻微波纹", "3 分钟", 180, "底面均匀金黄，面皮开始鼓起。", ["食用油", "中筋面粉"]),
      step("翻面煎透", "翻面补入剩余食用油，再盖盖煎 3 分钟；取一个切开检查中心无生面。", "小火", "不适用", "不适用", "3 分钟", 180, "两面金黄、面皮熟透，韭菜变软但仍鲜绿。", ["食用油", "中筋面粉", "韭菜", "鸡蛋"]),
    ],
    tips: ["韭菜必须彻底晾干并先裹芝麻油，最后才加盐，可减少出水。", "炒鸡蛋需完全放凉后再拌韭菜，避免余温把韭菜烫蔫。"],
    failurePoint: "馅料出水会导致封口不牢和煎制破皮，韭菜洗后一定要充分晾干。",
    safetyNote: "鸡蛋和面皮都要完全熟透；含虾皮，对甲壳类过敏者不要食用。",
    videoUrl: "https://www.bilibili.com/video/BV1kp4y1r78z/",
    videoTitle: "老师傅教你薄皮大馅韭菜盒子，再多的馅也不破皮，秘诀就在这个和面上",
    videoCreator: "品诺美食开课啦",
  },
  {
    slug: "fermented-rice-balls",
    title: "酒酿圆子",
    category: "甜点",
    tags: ["江南甜品"],
    featureTags: ["酒香清甜", "圆子软糯", "暖甜汤羹"],
    dietType: "素",
    nutritionRoles: ["甜点", "汤羹"],
    cookingMethod: "水煮",
    spiceLevel: 0,
    difficulty: 2,
    prepMinutes: 15,
    activeMinutes: 12,
    waitMinutes: 0,
    servings: 4,
    ingredients: [
      ingredient("糯米粉", 180, "g", "主料"),
      ingredient("温水", 135, "ml", "辅料", "和面用"),
      ingredient("甜酒酿", 300, "g", "辅料"),
      ingredient("清水", 900, "ml", "辅料", "煮汤用"),
      ingredient("鸡蛋", 1, "个", "辅料", "打散"),
      ingredient("冰糖", 25, "g", "调料"),
      ingredient("枸杞", 8, "g", "辅料", "冲洗"),
    ],
    steps: [
      step("揉成糯米面团", "温水分次加入糯米粉，先搅成絮状，再揉成柔软不开裂的面团。", "不适用", "温水", "不适用", "4 分钟", 240, "面团光滑，捏开边缘没有明显裂纹。", ["糯米粉", "温水"]),
      step("搓成小圆子", "面团搓成长条，分成约 3g 小剂子并逐个搓圆，未操作的面团盖住防干。", "不适用", "不适用", "不适用", "8 分钟", 480, "圆子直径约 1.2cm，表面光滑无裂口。", ["糯米粉"]),
      step("清水煮圆子", "锅中清水大火烧至沸腾，圆子分散下锅后轻推，转中火煮至全部浮起，再煮 1 分钟。", "中火", "沸水", "不适用", "4 分钟", 240, "圆子全部浮起，切开中心没有白色生粉芯。", ["清水", "糯米粉"], "糯米圆子必须完全煮透。"),
      step("加入酒酿冰糖", "转小火加入甜酒酿和冰糖，轻轻搅开，加热到汤面微沸。", "小火", "沸水", "不适用", "2 分钟", 120, "冰糖完全溶解，酒酿米粒均匀散开。", ["甜酒酿", "冰糖"]),
      step("淋蛋花", "蛋液沿锅边细流淋入，等待 10 秒后轻推形成蛋花。", "小火", "沸水", "不适用", "40 秒", 40, "蛋花完全凝固成薄片。", ["鸡蛋"], "蛋液必须完全凝固。"),
      step("枸杞收尾", "加入枸杞煮 30 秒后关火，静置 2 分钟再分碗。", "小火", "沸水", "不适用", "2 分钟", 120, "枸杞变软，圆子完整不糊汤。", ["枸杞"]),
    ],
    tips: ["圆子做得小而均匀，浮起后再煮 1 分钟更容易确保中心熟透。", "酒酿不宜大火久煮，微沸即可保留香气。"],
    failurePoint: "糯米面团过干会开裂，过湿会粘手；温水要分次加入。",
    safetyNote: "酒酿含少量酒精，儿童、孕妇及需避免酒精者不建议食用；糯米圆子黏性强，应小口慢食。",
    videoUrl: "https://www.bilibili.com/video/BV1mJ411P7a1/",
    videoTitle: "上海妈妈教你“家常酒酿圆子”做法，祝大家甜蜜团圆过中秋！",
    videoCreator: "上海妈妈私房菜",
  },
];

export const additionalRecipes: Recipe[] = additions.map(buildAdditionalRecipe);
