"use client";
import { Clipboard, Gift, RefreshCw, ShoppingBasket, Users } from "lucide-react";
import { useState } from "react";
import { useDietSettings } from "@/lib/use-diet-settings";
import { DIETARY_OPTIONS, type MenuResult } from "@/lib/blindbox";
import { RecipeCard } from "@/components/recipe-card";
import { Button } from "@/components/ui/button";

function displayAmount(amount:number,unit:string){return `${["个","只","张","颗","块"].includes(unit)?Math.ceil(amount):Math.round(amount*10)/10}${unit}`}
export function BlindBoxClient(){
 const {servings,setServings,babyAge,setBabyAge,exclusions,setExclusions,hydrated}=useDietSettings();const [maxMinutes,setMaxMinutes]=useState<0|30|60>(30);const [result,setResult]=useState<MenuResult|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [checked,setChecked]=useState<string[]>([]);const [copied,setCopied]=useState(false);
 async function generate(replaceIndex?:number){setBusy(true);setError("");try{const response=await fetch("/api/blindbox",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({servings,maxMinutes,exclusions,babyAge:babyAge||undefined,replaceIndex,currentSlugs:result?.recipes.map(r=>r.slug),avoidSlugs:replaceIndex===undefined?result?.recipes.map(r=>r.slug):undefined})});const data=await response.json() as MenuResult&{message?:string};if(!response.ok)throw new Error(data.message);setResult(data);setChecked([]);}catch(e){setError(e instanceof Error?e.message:"生成失败，请重试。")}finally{setBusy(false)}}
 async function copy(){if(!result)return;const groups=["主料","辅料","调料"].map(group=>`${group}\n${result.shoppingList.filter(i=>i.group===group).map(i=>`□ ${i.name} ${displayAmount(i.amount,i.unit)}`).join("\n")}`).join("\n\n");await navigator.clipboard.writeText(`Cook for Me｜${servings}人购物清单\n\n${groups}`);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 return <div className="page-shell py-8 md:py-14"><header className="relative overflow-hidden rounded-[30px] bg-gradient-to-br from-[#fff0e3] to-[#ffe1d1] px-6 py-9 text-[#3a251e] md:px-12 md:py-12"><div className="relative z-10 max-w-2xl"><h1 className="text-4xl font-black md:text-6xl">食物盲盒</h1><p className="mt-3 leading-7 text-muted-foreground">告诉我人数、可用时间和忌口，自动搭配蛋白质、蔬菜、汤与主食建议。时间按一个人操作估算，过敏限制绝不为了凑菜放宽。</p></div><span className="absolute -bottom-10 right-5 grid size-40 place-items-center rounded-[42px] bg-white/55 text-primary/80 rotate-[-8deg] md:right-14 md:size-48"><Gift className="size-24" strokeWidth={1.5}/><span className="absolute grid size-11 place-items-center rounded-full bg-[#f3c75b] text-2xl font-black text-[#5b391d]">?</span></span></header>
 <section className="mt-7 grid gap-5 rounded-[28px] border bg-card p-5 card-shadow md:grid-cols-3 md:p-7"><label className="font-bold"><span className="mb-2 flex items-center gap-2"><Users className="size-4 text-primary"/>就餐人数</span><select value={servings} onChange={e=>setServings(Number(e.target.value))} className="h-12 w-full rounded-2xl border bg-white px-4">{Array.from({length:8},(_,i)=><option key={i+1} value={i+1}>{i+1} 人</option>)}</select></label><label className="font-bold"><span className="mb-2 block">可用时间</span><select value={maxMinutes} onChange={e=>setMaxMinutes(Number(e.target.value) as 0|30|60)} className="h-12 w-full rounded-2xl border bg-white px-4"><option value={30}>30 分钟</option><option value={60}>60 分钟</option><option value={0}>不限</option></select></label><label className="font-bold"><span className="mb-2 block">宝宝月龄（可选）</span><select value={babyAge} onChange={e=>setBabyAge(Number(e.target.value))} className="h-12 w-full rounded-2xl border bg-white px-4"><option value={0}>不是宝宝餐</option>{Array.from({length:19},(_,i)=><option key={i+6} value={i+6}>{i+6} 月</option>)}</select></label><div className="md:col-span-3"><p className="mb-3 font-black">忌口与过敏</p><div className="flex flex-wrap gap-2">{DIETARY_OPTIONS.map(item=><button key={item} aria-pressed={exclusions.includes(item)} onClick={()=>setExclusions(v=>v.includes(item)?v.filter(x=>x!==item):[...v,item])} className={`min-h-11 rounded-full border px-4 text-sm font-bold ${exclusions.includes(item)?"border-primary bg-primary text-white":"bg-white"}`}>{item}</button>)}</div></div><Button disabled={busy||!hydrated} onClick={()=>generate()} className="h-14 rounded-2xl text-base font-black md:col-span-3">{busy?"正在搭配…":result?"换一桌菜单":"打开食物盲盒"}</Button>{error&&<p role="alert" className="md:col-span-3 rounded-2xl bg-[#fff0eb] p-4 text-sm font-bold text-destructive">{error}</p>}</section>
 {result&&<><section className="mt-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-bold text-primary">预计 {result.estimatedMinutes} 分钟 · {result.reason}</p><h2 className="mt-1 text-3xl font-black">这一桌，就这样做</h2><p className="mt-2 text-muted-foreground">主食建议：{result.stapleSuggestion}</p></div></div><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{result.recipes.map((recipe,index)=><div key={recipe.slug}><RecipeCard recipe={recipe}/><button disabled={busy} onClick={()=>generate(index)} className="mt-2 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border bg-white text-sm font-bold"><RefreshCw className="size-4"/>只换这道</button></div>)}</div></section>
 <section className="mt-12 rounded-[28px] border bg-[#fff9ee] p-5 md:p-8"><div className="flex items-center justify-between gap-3"><div><p className="flex items-center gap-2 font-bold text-primary"><ShoppingBasket/>SHOPPING LIST</p><h2 className="mt-1 text-2xl font-black">合并购物清单</h2></div><Button variant="outline" onClick={copy}><Clipboard/>{copied?"已复制":"复制"}</Button></div><div className="mt-6 grid gap-6 md:grid-cols-3">{(["主料","辅料","调料"] as const).map(group=><div key={group}><h3 className="mb-3 font-black">{group}</h3><div className="space-y-2">{result.shoppingList.filter(i=>i.group===group).map(item=>{const key=`${group}-${item.name}-${item.unit}`;return <label key={key} className="flex min-h-11 items-center gap-3 rounded-xl bg-white px-3"><input type="checkbox" checked={checked.includes(key)} onChange={()=>setChecked(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key])}/><span className={`flex-1 ${checked.includes(key)?"line-through opacity-50":""}`}>{item.name}</span><strong>{displayAmount(item.amount,item.unit)}</strong></label>})}</div></div>)}</div></section></>}
 </div>;
}
