"use client";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { useMemo, useState } from "react";
import { RecipeCard } from "./recipe-card";
import { categories, Recipe, totalMinutes } from "@/lib/recipes";

export function DiscoverClient({ recipes, initialQuery }: { recipes: Recipe[]; initialQuery: string }) {
  const [query, setQuery] = useState(initialQuery); const [category, setCategory] = useState("全部"); const [maxTime, setMaxTime] = useState(0); const [sort, setSort] = useState("popular");
  const filtered = useMemo(() => recipes.filter((r) => { const haystack = `${r.title}${r.summary}${r.category}${r.tags.join("")}${r.ingredients.map((i) => i.name).join("")}`; return (!query || haystack.includes(query)) && (category === "全部" || r.category === category) && (!maxTime || totalMinutes(r) <= maxTime); }).sort((a,b) => sort === "time" ? totalMinutes(a)-totalMinutes(b) : sort === "easy" ? a.difficulty-b.difficulty : b.weeklyLikes-a.weeklyLikes), [recipes, query, category, maxTime, sort]);
  return <div className="page-shell py-8 md:py-12"><div className="max-w-2xl"><p className="text-sm font-bold text-primary">慢慢逛，总会找到想吃的</p><h1 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">发现菜谱</h1><p className="mt-3 leading-7 text-muted-foreground">按菜名、食材、时间和类型筛选，每一道都写清楚用量与步骤。</p></div><div className="mt-8 flex h-14 items-center rounded-[18px] border bg-card px-4 card-shadow"><Search className="size-5 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索菜名或食材" className="h-full min-w-0 flex-1 bg-transparent px-3 outline-none" />{query && <button onClick={() => setQuery("")} className="grid size-10 place-items-center" aria-label="清除搜索"><X className="size-4" /></button>}</div>
    <div className="hide-scrollbar mt-5 flex gap-2 overflow-x-auto pb-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`h-11 shrink-0 rounded-full px-4 text-sm font-bold transition ${category === item ? "bg-primary text-white" : "border bg-card text-muted-foreground"}`}>{item}</button>)}</div>
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-y border-border/70 py-4"><div className="flex items-center gap-2 text-sm font-bold"><SlidersHorizontal className="size-4 text-primary" />{filtered.length} 道菜</div><div className="flex gap-2"><select value={maxTime} onChange={(e) => setMaxTime(Number(e.target.value))} className="h-10 rounded-full border bg-card px-3 text-sm font-semibold outline-none"><option value="0">不限时间</option><option value="15">15 分钟内</option><option value="30">30 分钟内</option><option value="60">60 分钟内</option></select><select value={sort} onChange={(e) => setSort(e.target.value)} className="h-10 rounded-full border bg-card px-3 text-sm font-semibold outline-none"><option value="popular">最近热门</option><option value="time">时间最短</option><option value="easy">难度最低</option></select></div></div>
    {filtered.length ? <div className="mt-6 grid grid-cols-2 gap-3.5 md:grid-cols-3 md:gap-5 lg:grid-cols-4">{filtered.map((recipe) => <RecipeCard key={recipe.slug} recipe={recipe} />)}</div> : <div className="mt-10 rounded-[28px] border border-dashed bg-card px-6 py-16 text-center"><div className="text-5xl">🍽️</div><h2 className="mt-4 text-xl font-black">暂时没有找到这道味道</h2><p className="mt-2 text-muted-foreground">换个食材或放宽时间再看看吧。</p><button onClick={() => { setQuery(""); setCategory("全部"); setMaxTime(0); }} className="mt-5 rounded-full bg-primary px-5 py-3 font-bold text-white">清除筛选</button></div>}
  </div>;
}
