"use client";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { RecipeCard } from "./recipe-card";
import { audienceCategories, categories, type Recipe, totalMinutes } from "@/lib/recipes";

export function DiscoverClient({ recipes, initialQuery, initialCategory="全部", initialTags=[] }: { recipes: Recipe[]; initialQuery: string; initialCategory?:string; initialTags?:string[] }) {
  const router=useRouter();const [query,setQuery]=useState(initialQuery);const [category,setCategory]=useState(initialCategory);const [tags,setTags]=useState(initialTags);const [maxTime,setMaxTime]=useState(0);const [sort,setSort]=useState("popular");const [difficulty,setDifficulty]=useState(0);const [spice,setSpice]=useState(-1);const [dietType,setDietType]=useState("");const [babyAge,setBabyAge]=useState(0);
  const filtered=useMemo(()=>recipes.filter(r=>{const haystack=`${r.title}${r.aliases.join("")}${r.summary}${r.category}${r.tags.join("")}${r.ingredients.map(i=>i.name).join("")}`;return(!query||haystack.includes(query))&&(category==="全部"||r.category===category)&&tags.every(t=>r.tags.includes(t))&&(!maxTime||totalMinutes(r)<=maxTime)&&(!difficulty||r.difficulty<=difficulty)&&(spice<0||r.spiceLevel===spice)&&(!dietType||r.dietType===dietType)&&(!babyAge||(r.babyAge&&babyAge>=r.babyAge.min&&babyAge<=r.babyAge.max));}).sort((a,b)=>sort==="time"?totalMinutes(a)-totalMinutes(b):sort==="easy"?a.difficulty-b.difficulty:sort==="total"?b.likes-a.likes:b.weeklyLikes-a.weeklyLikes),[recipes,query,category,tags,maxTime,sort,difficulty,spice,dietType,babyAge]);
  function sync(nextQuery=query,nextCategory=category,nextTags=tags){const p=new URLSearchParams();if(nextQuery)p.set("q",nextQuery);if(nextCategory!=="全部")p.set("category",nextCategory);nextTags.forEach(t=>p.append("tag",t));router.replace(`/discover${p.size?`?${p}`:""}`,{scroll:false});}
  function clear(){setQuery("");setCategory("全部");setTags([]);setMaxTime(0);setDifficulty(0);setSpice(-1);setDietType("");setBabyAge(0);router.replace("/discover",{scroll:false});}
  return <div className="page-shell py-8 md:py-12"><div className="max-w-2xl"><p className="text-sm font-bold text-primary">共 {recipes.length} 道家常菜</p><h1 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">发现菜谱</h1><p className="mt-3 leading-7 text-muted-foreground">按菜名、别名、食材、时间、人群与口味筛选，每道菜都可以查看备菜、步骤并进入烹饪模式。</p></div>
  <div className="mt-8 flex h-14 items-center rounded-[18px] border bg-card px-4 card-shadow"><Search className="size-5 text-muted-foreground"/><input value={query} onChange={e=>{setQuery(e.target.value);sync(e.target.value)}} placeholder="番茄、西红柿、鸡蛋…" className="h-full min-w-0 flex-1 bg-transparent px-3 outline-none"/>{query&&<button onClick={()=>{setQuery("");sync("")}} className="grid size-10 place-items-center" aria-label="清除搜索"><X className="size-4"/></button>}</div>
  <div className="hide-scrollbar mt-5 flex gap-2 overflow-x-auto pb-2">{categories.map(item=><button key={item} onClick={()=>{setCategory(item);sync(query,item)}} className={`h-11 shrink-0 rounded-full px-4 text-sm font-bold ${category===item?"bg-primary text-white":"border bg-card text-muted-foreground"}`}>{item}</button>)}</div>
  <div className="mt-3 flex flex-wrap gap-2">{audienceCategories.map(item=><button key={item} onClick={()=>{const next=tags.includes(item)?tags.filter(t=>t!==item):[...tags,item];setTags(next);sync(query,category,next)}} className={`min-h-11 rounded-full border px-4 text-sm font-bold ${tags.includes(item)?"border-[#5e8557] bg-[#e9f3e4] text-[#456341]":"bg-card"}`}>{item}</button>)}</div>
  <div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-y border-border/70 py-4"><div className="flex items-center gap-2 text-sm font-bold"><SlidersHorizontal className="size-4 text-primary"/>{filtered.length} 道菜</div><div className="flex flex-wrap gap-2"><select value={maxTime} onChange={e=>setMaxTime(Number(e.target.value))} className="h-11 rounded-full border bg-card px-3 text-sm font-semibold"><option value="0">不限时间</option><option value="15">15 分钟内</option><option value="30">30 分钟内</option><option value="60">60 分钟内</option></select><select value={difficulty} onChange={e=>setDifficulty(Number(e.target.value))} className="h-11 rounded-full border bg-card px-3 text-sm font-semibold"><option value="0">不限难度</option><option value="1">难度 1</option><option value="2">难度 ≤2</option><option value="3">难度 ≤3</option></select><select value={spice} onChange={e=>setSpice(Number(e.target.value))} className="h-11 rounded-full border bg-card px-3 text-sm font-semibold"><option value="-1">不限辣度</option><option value="0">不辣</option><option value="1">微辣</option><option value="2">中辣</option><option value="3">很辣</option></select><select value={dietType} onChange={e=>setDietType(e.target.value)} className="h-11 rounded-full border bg-card px-3 text-sm font-semibold"><option value="">不限荤素</option><option>荤</option><option>半荤素</option><option>素</option></select>{tags.includes("宝宝辅食")&&<select value={babyAge} onChange={e=>setBabyAge(Number(e.target.value))} className="h-11 rounded-full border bg-card px-3 text-sm font-semibold"><option value="0">选择月龄</option>{Array.from({length:19},(_,i)=><option key={i+6} value={i+6}>{i+6}月</option>)}</select>}<select value={sort} onChange={e=>setSort(e.target.value)} className="h-11 rounded-full border bg-card px-3 text-sm font-semibold"><option value="popular">最近 7 天</option><option value="total">总点赞</option><option value="time">时间最短</option><option value="easy">难度最低</option></select></div></div>
  {filtered.length?<div className="mt-6 grid grid-cols-2 gap-3.5 md:grid-cols-3 md:gap-5 lg:grid-cols-4">{filtered.map(recipe=><RecipeCard key={recipe.slug} recipe={recipe}/>)}</div>:<div className="mt-10 rounded-[28px] border border-dashed bg-card px-6 py-16 text-center"><div className="text-5xl">🍽️</div><h2 className="mt-4 text-xl font-black">当前条件没有合适菜谱</h2><p className="mt-2 text-muted-foreground">减少标签或放宽时间再看看。</p><button onClick={clear} className="mt-5 min-h-11 rounded-full bg-primary px-5 font-bold text-white">清除全部筛选</button></div>}</div>;
}
