import assert from "node:assert/strict";
import { getRecipe, recipes } from "../src/lib/recipes";
import { excluded, generateMenu, isProteinMain } from "../src/lib/blindbox";
import { dedicatedSteps } from "../src/lib/recipe-methods";
import { stepIngredientLabels } from "../src/lib/step-ingredients";

const recipe = (slug: string) => { const value = getRecipe(slug); assert.ok(value, `${slug} 必须存在`); return value; };
assert.equal(excluded(recipe("double-skin-milk"), ["奶过敏"]), true);
assert.equal(excluded(recipe("double-skin-milk"), ["不吃牛肉"]), false);
assert.equal(excluded(recipe("yangchun-noodles"), ["不吃猪肉"]), true);
assert.equal(excluded(recipe("twice-cooked-pork"), ["不吃猪肉"]), true);
assert.equal(excluded(recipe("garlic-broccoli"), ["海鲜过敏"]), true);
assert.equal(excluded(recipe("celery-squid"), ["海鲜过敏"]), true);
assert.equal(excluded(recipe("homemade-dumplings"), ["麸质限制"]), true);
assert.equal(excluded(recipe("scallion-oil-noodles"), ["大豆过敏"]), true);
assert.equal(excluded(recipe("sesame-cold-noodles"), ["芝麻过敏"]), true);
assert.equal(excluded(recipe("preserved-egg-pork-porridge"), ["蛋过敏"]), true);
assert.equal(recipe("mango-sago").dietType, "素", "芒果肉不是动物肉类");
assert.equal(recipe("scallion-oil-noodles").dietType, "素");
assert.equal(recipe("pumpkin-millet-porridge").dietType, "素");
assert.notEqual(recipe("oyster-mushroom").dietType, "素", "普通蚝油不是素食调料");
assert.equal(recipe("celery-lily").allergens.includes("大豆"), false, "西芹百合不应被通用酱油模板污染");
assert.equal(isProteinMain(recipe("garlic-broccoli")), false, "蚝油不能把西兰花变成蛋白质主菜");
assert.equal(isProteinMain(recipe("oyster-mushroom")), false);
assert.equal(isProteinMain(recipe("home-style-tofu")), true, "豆腐可以作为菜单蛋白质菜");
assert.equal(isProteinMain(recipe("tomato-scrambled-eggs")), true);
assert.equal(recipe("cola-chicken-wings").ingredients.some(i => i.name === "无糖可乐" || i.name === "清水"), false);
assert.ok(recipe("cola-chicken-wings").ingredients.some(i => i.name === "普通可乐" && i.amount === 330));
assert.ok(recipe("moo-shu-pork").steps.some(step => step.title === "鸡蛋先炒盛出"));
assert.ok(recipe("scallion-oil-noodles").steps.some(step => step.title === "小火熬葱油"));
assert.equal(recipe("scallion-oil-noodles").videoVerifiedAt, undefined, "仅元数据核对的视频不得伪造播放日期");
assert.ok(recipe("scallion-oil-noodles").videoMetadataCheckedAt);
const wings = recipe("cola-chicken-wings");
assert.ok(stepIngredientLabels(wings, wings.steps[4], wings.servings).every(i => i.amount === null), "回锅不能重复展示整道菜用量");
const eggs = recipe("tomato-scrambled-eggs");
assert.equal(stepIngredientLabels(eggs, eggs.steps[1], eggs.servings * 2).find(i => i.name === "食用油")?.amount, "20ml", "有明确分配的本步用油应正确换算");
assert.throws(() => generateMenu({ servings: 2, maxMinutes: 0, exclusions: ["不吃猪肉"], currentSlugs: ["twice-cooked-pork", "celery-lily"], replaceIndex: 1 }), /忌口/);
assert.throws(() => generateMenu({ servings: 2, maxMinutes: 0, exclusions: [], currentSlugs: ["cola-chicken-wings", "celery-lily"], replaceIndex: 20 }), /不一致/);
const menu = generateMenu({ servings: 2, maxMinutes: 0, exclusions: ["海鲜过敏", "不吃猪肉"] });
assert.ok(menu.recipes.every(r => !excluded(r, ["海鲜过敏", "不吃猪肉"])));
assert.ok(menu.recipes.every(r => r.category !== "甜点" && r.category !== "面食"), "甜点和主食不能代替正餐荤素搭配");
for (const servings of [2, 4, 6]) {
  const table = generateMenu({ servings, maxMinutes: 0, exclusions: [] });
  assert.equal(table.recipes.length, servings === 2 ? 2 : servings === 4 ? 4 : 5);
  assert.equal(table.recipes.filter(isProteinMain).length, servings === 2 ? 1 : 2);
  assert.ok(table.recipes.every(r => r.category !== "甜点" && !(r.category === "汤粥" && r.title.includes("粥"))));
}
assert.ok(!recipes.some(r => r.steps.some(step => step.title === "调好料汁")), "快炒菜不应再继承全部调料混在一起的通用流程");
assert.ok(recipes.every(r => !r.tags.includes("清淡") || r.editorialStatus === "reviewed"), "不辣不应自动等于清淡");
console.log(`✓ 忌口、过敏原、荤素、换菜边界及 ${Object.keys(dedicatedSteps).length} 道独立配方回归检查通过。`);
